const GET_VIDEO = "GET_VIDEO"
const GET_CATEGORY_NAME = "GET_CATEGORY_NAME"
const FILTER_RESET = "FILTER_RESET"
const GET_LIKED_VIDEO = "GET_LIKED_VIDEO"
const SAVED_LIKED_VIDEO = "SAVED_LIKED_VIDEO"
const REMOVE_LIKED_VIDEO = "REMOVE_LIKED_VIDEO"
const HISTORY_SAVED = "HISTORY_SAVED"
const CLEAR_HISTORY = "CLEAR_HISTORY"

export {GET_VIDEO, GET_CATEGORY_NAME, FILTER_RESET, GET_LIKED_VIDEO, SAVED_LIKED_VIDEO, REMOVE_LIKED_VIDEO, HISTORY_SAVED, CLEAR_HISTORY}